```{r}
library(tidyverse)
```

Here's an example of how to calculate z-scores using NCAA volleyball teams. We'll use match data for the 2023 season.

```{r}
matches23 <- read_csv("https://raw.githubusercontent.com/dwillis/NCAAWomensVolleyballData/main/data/ncaa_womens_volleyball_matchstats_2023.csv")

matches24 <- read_csv("https://raw.githubusercontent.com/dwillis/NCAAWomensVolleyballData/main/data/ncaa_womens_volleyball_matchstats_2024.csv")
```

Get Maryland's Aces

```{r}
matches23 |> 
  filter(team == "Maryland Terrapins, Terps") |> 
  group_by(result) |>
  summarize(
    avg_aces = mean(aces)
  )

matches24 |> 
  filter(team == "Maryland Terrapins, Terps") |> 
  group_by(result) |>
  summarize(
    avg_aces = mean(aces)
  )
```


T-test for significance
h0: no difference between the two years
ha: there is a difference between the two years

```{r}
umd_aces23 <- matches23 |> filter(team == "Maryland Terrapins, Terps") |> mutate(season=2023) #|>filter(date < '2023-09-12')
  
umd_aces24 <- matches24 |> filter(team == "Maryland Terrapins, Terps") |> mutate(season=2024)

result <- t.test(umd_aces23$aces, umd_aces24$aces, alternative = "two.sided", var.equal = TRUE)

print(result)
```

ANOVA test

```{r}
combined <- bind_rows(umd_aces23,umd_aces24)

combined$result <- factor(combined$result)
combined$season <- factor(combined$season)

anova_result <- aov(aces ~ result * season, data = combined)

summary(anova_result)
```







### Isolate the columns we might want to use for our metrics

```{r}
teamquality <- matches |> 
  select(team, kills, s, errors, total_attacks, assists, s_err, digs, ret_att, r_err, b_err)
```


### Calculate averages

```{r}
teamtotals <- teamquality |> 
  group_by(team) |> 
  summarise(
    avg_kills = mean(kills),
    avg_errors = mean(errors),
    avg_attacks = mean(total_attacks),
    avg_assists = mean(assists),
    avg_s_err = mean(s_err),
    avg_digs = mean(digs),
    avg_ret_att = mean(ret_att),
    avg_r_err = mean(r_err),
    avg_b_err = mean(b_err)
  )
```

### Create Z-Scores

```{r}
teamzscore <- teamtotals |> 
  mutate(
    kills_zscore = as.numeric(scale(avg_kills, center = TRUE, scale = TRUE)),
    errors_zscore = as.numeric(scale(avg_errors, center = TRUE, scale = TRUE)) * -1,
    s_err_zscore = as.numeric(scale(avg_s_err, center = TRUE, scale = TRUE)) * -1,
    digs_zscore = as.numeric(scale(avg_digs, center = TRUE, scale = TRUE)),
    TotalZscore = kills_zscore + errors_zscore + s_err_zscore + digs_zscore
  )
```

### Look at the results

```{r}
teamzscore |> select(team, TotalZscore, kills_zscore, errors_zscore, s_err_zscore, digs_zscore) |>  arrange(desc(TotalZscore))
```

