###WBB Notebook


```{r}
library(tidyverse)

```

###Z Scores
```{r}
gamelogs <- wbblogs24
```

```{r}
teamquality <- gamelogs |> 
  select(Conference, Team, TeamFGPCT, TeamTotalRebounds, OpponentFGPCT, OpponentTotalRebounds)
```

```{r}
teamtotals <- teamquality |> 
  filter(!is.na(OpponentFGPCT)) |>
  group_by(Conference, Team) |> 
  summarise(
    FGAvg = mean(TeamFGPCT), 
    ReboundAvg = mean(TeamTotalRebounds), 
    OppFGAvg = mean(OpponentFGPCT),
    OffRebAvg = mean(OpponentTotalRebounds)
    ) 
```

```{r}
teamzscore <- teamtotals |> 
  #scale gives us a value between -1 and 1
  mutate(
    FGzscore = as.numeric(scale(FGAvg, center = TRUE, scale = TRUE)),
    RebZscore = as.numeric(scale(ReboundAvg, center = TRUE, scale = TRUE)),
    OppZscore = as.numeric(scale(OppFGAvg, center = TRUE, scale = TRUE)) * -1, #gives us 'points' for a lower opponent z score  
    OppRebZScore = as.numeric(scale(OffRebAvg, center = TRUE, scale = TRUE)) * -1,
    TotalZscore = FGzscore + RebZscore + OppZscore + OppRebZScore
  )  
```

```{r}
teamzscore |> arrange(desc(TotalZscore))
```

```{r}
teamzscore |> 
  filter(Conference == "Big Ten WBB") |> 
  arrange(desc(TotalZscore)) |>
  select(Team, TotalZscore)
```


```{r}
powerfive_plus_one <- c("SEC WBB", "Big Ten WBB", "Pac-12 WBB", "Big 12 WBB", "ACC WBB", "Big East WBB")
teamzscore |> 
  filter(Conference %in% powerfive_plus_one) |> 
  arrange(desc(TotalZscore)) |>
  select(Team, TotalZscore)
```







----- 11/14/24
```{r}
teams <- read_csv("https://dwillis.github.io/sports-data-files/wbbstats25.csv")
```

```{r}
library(ggrepel)

umd <- teams |> filter(School == "Maryland")

big_ten <- teams |> filter(School %in% c('Illinois', 'Indiana', 'Iowa', 'Michigan', 'Michigan State', 'Ohio State', 'Minnesota', 'Nebraska', 'Northwestern', 'Rutgers', 'Southern California', 'UCLA', 'Oregon', 'Washington', 'Maryland'))

unbeaten <- teams |> filter(OverallLosses == 0)

avg_srs <- unbeaten |> filter(!is.na(OverallSRS)) |> summarize(mean(OverallSRS)) |> pull(1)

avg_sos <- unbeaten |> filter(!is.na(OverallSOS)) |> summarize(mean(OverallSOS)) |> pull(1)

ggplot() +
  geom_point(data=unbeaten, aes(x = OverallSRS, y= OverallSOS, size = OverallWins), color="grey") +
  geom_point(data=big_ten, aes(x = OverallSRS, y= OverallSOS, size = OverallWins), color="yellow") +
  geom_point(data=umd, aes(x = OverallSRS, y= OverallSOS, size = OverallWins), color="red") + 
  geom_vline(xintercept = avg_srs) +
  geom_hline(yintercept = avg_sos) +
  geom_text_repel(
    data=big_ten, 
    aes(x=OverallSRS, y=OverallSOS, label=School)
  )

```







